### ISSUE TITLE
Add check_argument function/set of functions

### ISSUE THREAD

**Issue by beckerbenj** [weirichs/eatTools#6]
Input validation is a repetitive task across functions and packages. Check available package options and, if insufficient, write an own set of functions.

**Comment by beckerbenj** [comment]
Prior research should be done on existing package solutions

**Comment by beckerbenj** [comment]
Implement examples, open discussion with all eat-package authors.

**Comment by grewered** [comment]
EG hat einen Vorschlag rumgeschickt, wir reviewen.
    Vertretung für BB?

**Comment by beckerbenj** [comment]
`checkmate` as package/framework of choice. @grewered will implement/modify checks function by function with separate branches for each change. @weirichs and @sachseka will review; first review maybe during group meeting?

**Comment by grewered** [comment]
I looked at (some of) the other functions. They seem more comlicated than 'seq2()' and I guess I'd need some time and/or help figuring them out, and what kind of checks they need. Also if they need new checks at all, as some already have some. 

Should I change the checks to use checkmate code, as it may be less lines?

the function 'addLeadingZerosToCharInt()', for instance, already checks for data frame and character input, so I don't think it would make a lot of sense changing that, but I'm not sure.
![grafik](https://github.com/weirichs/eatTools/assets/135963233/69be8ca9-de85-46e4-982d-4656b51cf698)

-------------

And with the next functions in the file, 'asNumericIfPossible'.R, there seem to be several functions, but I don't think I understood them fully. 

Do some functions use other functions in the package? 
And do you have suggestions with which one(s) I should start?
Because going in order doesn't seem to be the best way, although it would be easiest to keep track of, which ones are already implemented.

**Comment by weirichs** [comment]
I would suggest to reduce the code quantity, whenever possible. However, `addLeadingZerosToCharInt()` looks fine and maybe Karoline would prefer to keep her version. 

`asNumericIfPossible()` is different insofar it is a generic function. What the function does, depends on the input `x`. If `x` is `data.frame`, the behavior of `asNumericIfPossible()` if different from the behavior if `x` is a character vector. The different behaviors are represented by the additional functions `asNumericIfPossible.character()`, `asNumericIfPossible.data.frame()` etc. 

Due to S3 classes, I would not add checks for `x`. Checks might be added for the arguments `maintain.factor.scores`, `force.string`, `transform.factors`, and `varName`, for example.

**Comment by sachseka** [comment]
> the function `addLeadingZerosToCharInt()`, for instance, already checks for data frame and character input, so I don't think it would make a lot of sense changing that, but I'm not sure. 

I'm fine with either way (leaving checks as is or change2checkmate ;))

**Comment by grewered** [comment]
I've went through all functions now. Only #23 throughs an error I don't understand. The rest should be fine, unless you have some issues @sachseka @weirichs
